### ISSUE TITLE
로고 디자인

### ISSUE THREAD

**Issue by ybkimm** [osamhack2020/WEB_mindpill_mindpill#23]
제출 양식에 들어가야하니 팀 로고 겸 서비스 로고가 있어야 할 것 같네요.

**Comment by clo3olb** [comment]
로고는 제가 이번주에 제작해서 올리면 의견 같이 토의해보면 좋을 것 같습니다.

**Comment by ybkimm** [comment]
그럼 저도 시간날 때 하나 만들어서 올려볼게요.

서로 보고 괜찮은 안을 하나 만들어보는게 좋겠네요.

**Comment by ybkimm** [comment]
![design](https://user-images.githubusercontent.com/48612325/96358594-e9ec7180-1143-11eb-8ffe-45735f421ae4.png)

![english](https://user-images.githubusercontent.com/48612325/96358595-eb1d9e80-1143-11eb-9a4d-ebc0857aee42.png) ![korean](https://user-images.githubusercontent.com/48612325/96358596-eb1d9e80-1143-11eb-83af-e3430f86974d.png)

폰트는 [양진체](http://supernovice.org/font/?ckattempt=1)입니다.
