### ISSUE TITLE
소개 및 시연 영상 제작

### ISSUE THREAD

**Issue by ybkimm** [osamhack2020/WEB_mindpill_mindpill#24]
제출 양식에 포함되야 하니 필요합니다.

시연 영상은 스마트폰 화면 녹화 앱 가져와서 찍던가 하고, 편집은 휴가든 외출 나가서 PC방 갈 수 있으면 거기다 에펙깔고 해야 할 것 같네요. 코로나 때문에 나갈 수 있을지는 모르겠지만...

**Comment by clo3olb** [comment]
영상 퀄리티는 어느정도 생각하시나요? 어느 정도 간단한 수준에서 하려면, 제가 영상쪽에서 일했었던 적도 있고(물론 노트북이 없어서 제대로 할 수는 없지만) 가족 중에서 영상부분 좀 도와줄 수 있는 분이 있어서...

**Comment by ybkimm** [comment]
일단 간단하게 시연영상에 로고 페이드아웃 되는 정도면 만들 수 있지 않을까 해서 그 정도만 생각하고 있었습니다. 사실 다른 팀이라고 그 이상 나올 것 같지는 않기도 하고요.

도와주실 분이 있다면야 저로썬 환영입니다.
