### ISSUE TITLE
모바일 디바이스 지원

### ISSUE THREAD

**Issue by ybkimm** [osamhack2020/WEB_mindpill_mindpill#47]
모바일 디바이스에서 보면 화면이 잘리는 등의 문제가 발생하네요.

나중에 완전히 CSS를 다시 쓸 필요가 있을 것 같습니다.

**Comment by clo3olb** [comment]
모바일도 지원하실 생각인가요?
저는 국방망 컴퓨터로만 염두에 두고 있었습니다. 모바일도 하실 생각이면 개발이 완료되고 수정을 해야할 것 같네요

**Comment by ybkimm** [comment]
저는 필요하다고 생각합니다. 어쨌든 국방망에서 돌리는 게 아니니까요.

**Comment by clo3olb** [comment]
멘토님은 모바일전용으로 앱을 제작하고 기능을 줄이고 완성을 한 뒤에 발표자료 준비를 원하시는데 어떻게 생각하시나요? 저도 시간이 많이 없다는 부분은 동의하고 있지만, 용빈님 의견이 필요할 것 같습니다.

**Comment by ybkimm** [comment]
같은 생각입니다. 둘 중 하나에 집중할 필요는 있어보이네요. 다만 저희가 앱을 이제와서 만들수는 없겠죠.

프로젝트가 웹 기반이니 그냥 부트스트랩이나 Bulma같은 CSS 프레임워크 때려박고 모바일 위주로 개발하면서 PC는 덤으로 된다는 느낌이면 충분하지 않을까 싶네요.

기능은 일단 최소한 시연에 필요한 API 위주로 만들고 있습니다. 최종적으로는 `./mindpill setup-database` 명령으로 그냥 아예 시연용 데이터를 바로 세팅할 수 있게 하려 합니다. (이 부분은 SQL 파일을 안 쓰고 [ent](https://entgo.io)를 쓰고 있어서 별로 시간도 안 잡아 먹고요.)
