### ISSUE TITLE
api에서 response가 500(Internal Server Error)가 나오는 문제

### ISSUE THREAD

**Issue by clo3olb** [osamhack2020/WEB_mindpill_mindpill#52]
api를 요청할 때마다 500으로만 응답되는데, 400으로 답해야 할 것 같은 요청에도 500으로만 응답이 옵니다. 
Maria DB랑 MySql 설치하고 올려주셨던 DB를 복구시켜서 열었는데도 같은 증상이 나오는데, 혹시 제가 놓친 부분이 있을까요?

**Comment by ybkimm** [comment]
DB 스키마가 수시로 바뀝니다. 그래서 make setup-database라는 명령도 만들어뒀고요. 이 명령으로 DB 변경시에도 마이그레이션이 가능합니다. 미리 말씀드렸어야 했는데 제가 실수했네요.

**Comment by ybkimm** [comment]
만약 DB 문제가 아닌데 그런 경우는 그냥 제가 귀찮아서 대충 때워둔 것일 확률이 높습니다.

이런 경우라면 제가 어디서 문제가 발생했는지 알아야 하니 어떤 URL에 어떤 데이터로 요청했는지도(크롬 네트워크 디버그 탭에 나옵니다) 같이 보내주시면 감사하겠습니다.

혹시 안되면 다시 이슈 열어주세요!
