### ISSUE TITLE
API: 프론트에서 요구되는 API 목록

### ISSUE THREAD

**Issue by clo3olb** [osamhack2020/WEB_mindpill_mindpill#57]
1. Create_Token 에서 Access Token 요청에 대한 응답에 현재 로그인을 요청한 사용자의 정보가 포함되어 왔으면 합니다.
   - 로그인 된 사용자의 권한(서비스 관리자, 부대 관리자, 상담관, 지휘관, 피상담자)에 맞춰서 표시되는 정보를 변경해야 합니다.

**Comment by ybkimm** [comment]
1. 현재 그 목적으로 사용 가능한 `describe_token` 엔드포인트가 있습니다. `create_token` 이후 바로 호출해주시면 됩니다.
2. 토큰에 뭘 더 넣기가 애매해서 현재는 기본적인 사용자 정보랑 권한 정보 정도만 넣어뒀습니다. 어느 그룹(부대)에 속한 사용자인지, 어느 그룹의 관리자인지 혹은 상담관인지 등등 관련된 정보가 나옵니다. 사용자에 대해 좀 더 자세한 정보가 필요하다면 `describe_user` 엔드포인트를 사용하시면 됩니다.

현재 문서화가 잘 되어있지 않습니다. 급한 파트만 마무리 하고 문서화도 진행을 시켜놓을게요. 혹시 두 API보다 더 자세한 데이터가 필요하다면 말씀해주세요.

**Comment by clo3olb** [comment]
회원가입 하는 사람들이 부대를 선택해야 하는데, 부대목록을 가져올 수 있는 API도 있나요?

**Comment by ybkimm** [comment]
해당 기능 구현해서 추가했습니다.
